logging:
  level:
    com.client.api: DEBUG

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '#Khumalo01'
    dbcp2:
      driver: org.postgesql.Driver
      max-total: 20
      initial-size: 7
      pool-prepared-statements: true
      driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false